### ISSUE TITLE
Wrong filename doesn't trigger error

### ISSUE THREAD

**Issue by Jean85** [drone-plugins/drone-sftp#11]
After fixing #10 on my build, I stepped on an other bug:

```
[info] Pulling image plugins/drone-sftp:latest
Connection successful. 
ls: no such file or directory: /drone/src/host/vendor/project/docker/docker-composer.yml.production

Upload successful
```

As you can see, I've made a small typo in the filename (`docker-composeR`) and the upload couldn't be done. The upload was marked successful anyway, and the build proceeded.

Is this intended behavior?

**Comment by athieriot** [comment]
Hi there !

No. I don't think it's intended unfortunately :(
When I refactored drone-artifactory, I made the Promises properly bubble up the errors and this plugin would definitively benefit from this kind of clean up.

**Comment by tboerger** [comment]
This plugin is not really actively maintained anymore, I gonna close that issue.
