### ISSUE TITLE
 Cannot find module '/drone/src/index.js'

### ISSUE THREAD

**Issue by fr4n3r** [drone-plugins/drone-sftp#13]
Hi Im having problems with the plugin and i don't know what is wrong. 

My .drone.yml has the following settings:
...
sftp_upload:
    image: plugins/drone-sftp
    host: $$SFTP_HOST
    username: $$SFTP_USERNAME
    password: $$SFTP_PASSWORD
    destination_path: /root/docker/
    files:
     - /drone/src/.drone/docker-compose.yml
...

And the error is:

module.js:328
    throw err;
    ^
Error: Cannot find module '/drone/src/index.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

thanks in advance

**Comment by athieriot** [comment]
What version of Drone are you using?

**Comment by fr4n3r** [comment]
0.5

**Comment by athieriot** [comment]
Yeah. This plugin is only for 0.4 at the moment

**Comment by fr4n3r** [comment]
Oh!, ok thanks for the quick answer.

**Comment by tboerger** [comment]
And even if you are using 0.5 the config for it won't work anyway since the secret management entirely changed ;)

**Comment by tboerger** [comment]
This plugin is not really actively maintained anymore, I gonna close that issue.
