### ISSUE TITLE
drone 0.5 instructions?

### ISSUE THREAD

**Issue by fommil** [drone-plugins/drone-sftp#14]
Is this plugin compatible with drone 0.5?

Could you please also let me know what is used for the default password if none is provided? I have no idea how my 0.4 sftp deploys were working. I must have passed in some blob in the secure file.

**Comment by athieriot** [comment]
Hi there !

No that plugin is not compatible with Drone 0.5 at the moment.

If there is no password, it's going to use an SSH key. Drone generate a public/private pair per projects so you must have added one on your server.

**Comment by fommil** [comment]
Ah! Of course. That was driving me crazy.
