### ISSUE TITLE
certificate credentials

### ISSUE THREAD

**Issue by fommil** [drone-plugins/drone-sftp#8]
any thoughts on how certificate based login could work? I'm not sure how drone would be able to make the certificate file available.

**Comment by athieriot** [comment]
For each project, Drone creates its own public/private key. You can find the key to configure your server with in the GUI, in the project settings.

Drone Sftp is ready to use that.

**Comment by fommil** [comment]
ok cool, that's interesting, I hadn't thought about generating a new key.
